`timescale 1ns/1ps

module mbtrain_tb_top;
  import uvm_pkg::*;
  import mbtrain_env_pkg::*;
  import mbtrain_seq_pkg::*;
  import mbtrain_test_pkg::*;

  logic clock;
  logic reset;

  initial begin clock = 0; forever #5 clock = ~clock; end
  initial begin reset = 1; #20 reset = 0; end

  mbtrain_if vif(clock, reset);

  MBTrainSM dut (
    .clock  (clock),
    .reset  (reset),

    .io_goToState_valid              (vif.goToState_valid),
    .io_goToState_bits               (vif.goToState_bits),
    .io_negotiatedMaxDataRate        (vif.negotiatedMaxDataRate),
    .io_pllLock                      (vif.pllLock),
    .io_phyInRetrain                 (vif.phyInRetrain),
    .io_interpretBy8Lane             (vif.interpretBy8Lane),
    .io_maxErrorThresholdPerLane     (vif.maxErrorThresholdPerLane),
    .io_changeInRuntimeLinkCtrlRegs  (vif.changeInRuntimeLinkCtrlRegs),
    .io_currLocalTxFunctionalLanes   (vif.currLocalTxFunctionalLanes),
    .io_currRemoteTxFunctionalLanes  (vif.currRemoteTxFunctionalLanes),

    .io_currentState                 (vif.currentState),
    .io_freqSel_valid                (vif.freqSel_valid),
    .io_freqSel_bits                 (vif.freqSel_bits),
    .io_doElectricalIdleTx           (vif.doElectricalIdleTx),
    .io_doElectricalIdleRx           (vif.doElectricalIdleRx),
    .io_clearPhyInRetrainFlag        (vif.clearPhyInRetrainFlag),
    .io_txWidthChanged               (vif.txWidthChanged),
    .io_rxWidthChanged               (vif.rxWidthChanged),
    .io_newLocalFunctionalLanes      (vif.newLocalFunctionalLanes),
    .io_newRemoteFunctionalLanes     (vif.newRemoteFunctionalLanes),
    .io_rxClkCalSendFwClkPattern     (vif.rxClkCalSendFwClkPattern),
    .io_rxClkCalSendTrkPattern       (vif.rxClkCalSendTrkPattern),

    .io_mbLaneCtrlIo_txDataEn_0      (vif.mbLaneCtrl_txDataEn[0]),
    .io_mbLaneCtrlIo_txDataEn_1      (vif.mbLaneCtrl_txDataEn[1]),
    .io_mbLaneCtrlIo_txDataEn_2      (vif.mbLaneCtrl_txDataEn[2]),
    .io_mbLaneCtrlIo_txDataEn_3      (vif.mbLaneCtrl_txDataEn[3]),
    .io_mbLaneCtrlIo_txDataEn_4      (vif.mbLaneCtrl_txDataEn[4]),
    .io_mbLaneCtrlIo_txDataEn_5      (vif.mbLaneCtrl_txDataEn[5]),
    .io_mbLaneCtrlIo_txDataEn_6      (vif.mbLaneCtrl_txDataEn[6]),
    .io_mbLaneCtrlIo_txDataEn_7      (vif.mbLaneCtrl_txDataEn[7]),
    .io_mbLaneCtrlIo_txDataEn_8      (vif.mbLaneCtrl_txDataEn[8]),
    .io_mbLaneCtrlIo_txDataEn_9      (vif.mbLaneCtrl_txDataEn[9]),
    .io_mbLaneCtrlIo_txDataEn_10     (vif.mbLaneCtrl_txDataEn[10]),
    .io_mbLaneCtrlIo_txDataEn_11     (vif.mbLaneCtrl_txDataEn[11]),
    .io_mbLaneCtrlIo_txDataEn_12     (vif.mbLaneCtrl_txDataEn[12]),
    .io_mbLaneCtrlIo_txDataEn_13     (vif.mbLaneCtrl_txDataEn[13]),
    .io_mbLaneCtrlIo_txDataEn_14     (vif.mbLaneCtrl_txDataEn[14]),
    .io_mbLaneCtrlIo_txDataEn_15     (vif.mbLaneCtrl_txDataEn[15]),
    .io_mbLaneCtrlIo_txClkEn         (vif.mbLaneCtrl_txClkEn),
    .io_mbLaneCtrlIo_txValidEn       (vif.mbLaneCtrl_txValidEn),
    .io_mbLaneCtrlIo_txTrackEn       (vif.mbLaneCtrl_txTrackEn),
    .io_mbLaneCtrlIo_rxDataEn_0      (vif.mbLaneCtrl_rxDataEn[0]),
    .io_mbLaneCtrlIo_rxDataEn_1      (vif.mbLaneCtrl_rxDataEn[1]),
    .io_mbLaneCtrlIo_rxDataEn_2      (vif.mbLaneCtrl_rxDataEn[2]),
    .io_mbLaneCtrlIo_rxDataEn_3      (vif.mbLaneCtrl_rxDataEn[3]),
    .io_mbLaneCtrlIo_rxDataEn_4      (vif.mbLaneCtrl_rxDataEn[4]),
    .io_mbLaneCtrlIo_rxDataEn_5      (vif.mbLaneCtrl_rxDataEn[5]),
    .io_mbLaneCtrlIo_rxDataEn_6      (vif.mbLaneCtrl_rxDataEn[6]),
    .io_mbLaneCtrlIo_rxDataEn_7      (vif.mbLaneCtrl_rxDataEn[7]),
    .io_mbLaneCtrlIo_rxDataEn_8      (vif.mbLaneCtrl_rxDataEn[8]),
    .io_mbLaneCtrlIo_rxDataEn_9      (vif.mbLaneCtrl_rxDataEn[9]),
    .io_mbLaneCtrlIo_rxDataEn_10     (vif.mbLaneCtrl_rxDataEn[10]),
    .io_mbLaneCtrlIo_rxDataEn_11     (vif.mbLaneCtrl_rxDataEn[11]),
    .io_mbLaneCtrlIo_rxDataEn_12     (vif.mbLaneCtrl_rxDataEn[12]),
    .io_mbLaneCtrlIo_rxDataEn_13     (vif.mbLaneCtrl_rxDataEn[13]),
    .io_mbLaneCtrlIo_rxDataEn_14     (vif.mbLaneCtrl_rxDataEn[14]),
    .io_mbLaneCtrlIo_rxDataEn_15     (vif.mbLaneCtrl_rxDataEn[15]),
    .io_mbLaneCtrlIo_rxClkEn         (vif.mbLaneCtrl_rxClkEn),
    .io_mbLaneCtrlIo_rxValidEn       (vif.mbLaneCtrl_rxValidEn),
    .io_mbLaneCtrlIo_rxTrackEn       (vif.mbLaneCtrl_rxTrackEn),

    .io_fsmCtrl_start                (vif.fsmCtrl_start),
    .io_fsmCtrl_substateTransitioning(vif.fsmCtrl_substateTransitioning),
    .io_fsmCtrl_error                (vif.fsmCtrl_error),
    .io_fsmCtrl_done                 (vif.fsmCtrl_done),

    .io_requesterSbLaneIo_tx_ready     (vif.requesterSbLaneIo_tx_ready),
    .io_requesterSbLaneIo_tx_valid     (vif.requesterSbLaneIo_tx_valid),
    .io_requesterSbLaneIo_tx_bits_data (vif.requesterSbLaneIo_tx_bits_data),
    .io_requesterSbLaneIo_rx_ready     (vif.requesterSbLaneIo_rx_ready),
    .io_requesterSbLaneIo_rx_valid     (vif.requesterSbLaneIo_rx_valid),
    .io_requesterSbLaneIo_rx_bits_data (vif.requesterSbLaneIo_rx_bits_data),

    .io_responderSbLaneIo_tx_ready     (vif.responderSbLaneIo_tx_ready),
    .io_responderSbLaneIo_tx_valid     (vif.responderSbLaneIo_tx_valid),
    .io_responderSbLaneIo_tx_bits_data (vif.responderSbLaneIo_tx_bits_data),
    .io_responderSbLaneIo_rx_ready     (vif.responderSbLaneIo_rx_ready),
    .io_responderSbLaneIo_rx_valid     (vif.responderSbLaneIo_rx_valid),
    .io_responderSbLaneIo_rx_bits_data (vif.responderSbLaneIo_rx_bits_data),

    .io_txPtTestReqIntfIo_done                         (vif.txPtTestReq_done),
    .io_txPtTestReqIntfIo_ptTestResults_valid          (vif.txPtTestReq_ptTestResults_valid),
    .io_txPtTestReqIntfIo_ptTestResults_bits_0         (vif.txPtTestReq_ptTestResults_bits[0]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_1         (vif.txPtTestReq_ptTestResults_bits[1]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_2         (vif.txPtTestReq_ptTestResults_bits[2]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_3         (vif.txPtTestReq_ptTestResults_bits[3]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_4         (vif.txPtTestReq_ptTestResults_bits[4]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_5         (vif.txPtTestReq_ptTestResults_bits[5]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_6         (vif.txPtTestReq_ptTestResults_bits[6]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_7         (vif.txPtTestReq_ptTestResults_bits[7]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_8         (vif.txPtTestReq_ptTestResults_bits[8]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_9         (vif.txPtTestReq_ptTestResults_bits[9]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_10        (vif.txPtTestReq_ptTestResults_bits[10]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_11        (vif.txPtTestReq_ptTestResults_bits[11]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_12        (vif.txPtTestReq_ptTestResults_bits[12]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_13        (vif.txPtTestReq_ptTestResults_bits[13]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_14        (vif.txPtTestReq_ptTestResults_bits[14]),
    .io_txPtTestReqIntfIo_ptTestResults_bits_15        (vif.txPtTestReq_ptTestResults_bits[15]),
    .io_txPtTestReqIntfIo_start                        (vif.txPtTestReq_start),
    .io_txPtTestReqIntfIo_linkTrainingParameters_clockPhase    (vif.txPtTestReq_clockPhase),
    .io_txPtTestReqIntfIo_linkTrainingParameters_dataPattern   (vif.txPtTestReq_dataPattern),
    .io_txPtTestReqIntfIo_linkTrainingParameters_validPattern  (vif.txPtTestReq_validPattern),
    .io_txPtTestReqIntfIo_linkTrainingParameters_patternMode   (vif.txPtTestReq_patternMode),
    .io_txPtTestReqIntfIo_linkTrainingParameters_iterationCount(vif.txPtTestReq_iterationCount),
    .io_txPtTestReqIntfIo_linkTrainingParameters_idleCount     (vif.txPtTestReq_idleCount),
    .io_txPtTestReqIntfIo_linkTrainingParameters_burstCount    (vif.txPtTestReq_burstCount),
    .io_txPtTestReqIntfIo_linkTrainingParameters_maxErrorThreshold(vif.txPtTestReq_maxErrorThreshold),
    .io_txPtTestReqIntfIo_linkTrainingParameters_comparisonMode(vif.txPtTestReq_comparisonMode),
    .io_txPtTestReqIntfIo_patternType                          (vif.txPtTestReq_patternType),

    .io_txEyeSweepReqIntfIo_done                        (vif.txEyeSweepReq_done),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_valid   (vif.txEyeSweepReq_eyeSweepTestResults_valid),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_0  (vif.txEyeSweepReq_eyeSweepTestResults_bits[0]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_1  (vif.txEyeSweepReq_eyeSweepTestResults_bits[1]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_2  (vif.txEyeSweepReq_eyeSweepTestResults_bits[2]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_3  (vif.txEyeSweepReq_eyeSweepTestResults_bits[3]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_4  (vif.txEyeSweepReq_eyeSweepTestResults_bits[4]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_5  (vif.txEyeSweepReq_eyeSweepTestResults_bits[5]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_6  (vif.txEyeSweepReq_eyeSweepTestResults_bits[6]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_7  (vif.txEyeSweepReq_eyeSweepTestResults_bits[7]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_8  (vif.txEyeSweepReq_eyeSweepTestResults_bits[8]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_9  (vif.txEyeSweepReq_eyeSweepTestResults_bits[9]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_10 (vif.txEyeSweepReq_eyeSweepTestResults_bits[10]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_11 (vif.txEyeSweepReq_eyeSweepTestResults_bits[11]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_12 (vif.txEyeSweepReq_eyeSweepTestResults_bits[12]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_13 (vif.txEyeSweepReq_eyeSweepTestResults_bits[13]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_14 (vif.txEyeSweepReq_eyeSweepTestResults_bits[14]),
    .io_txEyeSweepReqIntfIo_eyeSweepTestResults_bits_15 (vif.txEyeSweepReq_eyeSweepTestResults_bits[15]),
    .io_txEyeSweepReqIntfIo_start                        (vif.txEyeSweepReq_start),
    .io_txEyeSweepReqIntfIo_linkTrainingParameters_clockPhase    (vif.txEyeSweepReq_clockPhase),
    .io_txEyeSweepReqIntfIo_linkTrainingParameters_dataPattern   (vif.txEyeSweepReq_dataPattern),
    .io_txEyeSweepReqIntfIo_linkTrainingParameters_validPattern  (vif.txEyeSweepReq_validPattern),
    .io_txEyeSweepReqIntfIo_linkTrainingParameters_patternMode   (vif.txEyeSweepReq_patternMode),
    .io_txEyeSweepReqIntfIo_linkTrainingParameters_iterationCount(vif.txEyeSweepReq_iterationCount),
    .io_txEyeSweepReqIntfIo_linkTrainingParameters_idleCount     (vif.txEyeSweepReq_idleCount),
    .io_txEyeSweepReqIntfIo_linkTrainingParameters_burstCount    (vif.txEyeSweepReq_burstCount),
    .io_txEyeSweepReqIntfIo_linkTrainingParameters_maxErrorThreshold(vif.txEyeSweepReq_maxErrorThreshold),
    .io_txEyeSweepReqIntfIo_linkTrainingParameters_comparisonMode(vif.txEyeSweepReq_comparisonMode),
    .io_txEyeSweepReqIntfIo_patternType                          (vif.txEyeSweepReq_patternType),

    .io_rxPtTestReqIntfIo_done                         (vif.rxPtTestReq_done),
    .io_rxPtTestReqIntfIo_ptTestResults_valid          (vif.rxPtTestReq_ptTestResults_valid),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_0         (vif.rxPtTestReq_ptTestResults_bits[0]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_1         (vif.rxPtTestReq_ptTestResults_bits[1]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_2         (vif.rxPtTestReq_ptTestResults_bits[2]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_3         (vif.rxPtTestReq_ptTestResults_bits[3]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_4         (vif.rxPtTestReq_ptTestResults_bits[4]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_5         (vif.rxPtTestReq_ptTestResults_bits[5]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_6         (vif.rxPtTestReq_ptTestResults_bits[6]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_7         (vif.rxPtTestReq_ptTestResults_bits[7]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_8         (vif.rxPtTestReq_ptTestResults_bits[8]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_9         (vif.rxPtTestReq_ptTestResults_bits[9]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_10        (vif.rxPtTestReq_ptTestResults_bits[10]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_11        (vif.rxPtTestReq_ptTestResults_bits[11]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_12        (vif.rxPtTestReq_ptTestResults_bits[12]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_13        (vif.rxPtTestReq_ptTestResults_bits[13]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_14        (vif.rxPtTestReq_ptTestResults_bits[14]),
    .io_rxPtTestReqIntfIo_ptTestResults_bits_15        (vif.rxPtTestReq_ptTestResults_bits[15]),
    .io_rxPtTestReqIntfIo_start                        (vif.rxPtTestReq_start),
    .io_rxPtTestReqIntfIo_linkTrainingParameters_clockPhase    (vif.rxPtTestReq_clockPhase),
    .io_rxPtTestReqIntfIo_linkTrainingParameters_dataPattern   (vif.rxPtTestReq_dataPattern),
    .io_rxPtTestReqIntfIo_linkTrainingParameters_validPattern  (vif.rxPtTestReq_validPattern),
    .io_rxPtTestReqIntfIo_linkTrainingParameters_patternMode   (vif.rxPtTestReq_patternMode),
    .io_rxPtTestReqIntfIo_linkTrainingParameters_iterationCount(vif.rxPtTestReq_iterationCount),
    .io_rxPtTestReqIntfIo_linkTrainingParameters_idleCount     (vif.rxPtTestReq_idleCount),
    .io_rxPtTestReqIntfIo_linkTrainingParameters_burstCount    (vif.rxPtTestReq_burstCount),
    .io_rxPtTestReqIntfIo_linkTrainingParameters_maxErrorThreshold(vif.rxPtTestReq_maxErrorThreshold),
    .io_rxPtTestReqIntfIo_linkTrainingParameters_comparisonMode(vif.rxPtTestReq_comparisonMode),
    .io_rxPtTestReqIntfIo_patternType                          (vif.rxPtTestReq_patternType),

    .io_rxEyeSweepReqIntfIo_done                        (vif.rxEyeSweepReq_done),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_valid   (vif.rxEyeSweepReq_eyeSweepTestResults_valid),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_0  (vif.rxEyeSweepReq_eyeSweepTestResults_bits[0]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_1  (vif.rxEyeSweepReq_eyeSweepTestResults_bits[1]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_2  (vif.rxEyeSweepReq_eyeSweepTestResults_bits[2]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_3  (vif.rxEyeSweepReq_eyeSweepTestResults_bits[3]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_4  (vif.rxEyeSweepReq_eyeSweepTestResults_bits[4]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_5  (vif.rxEyeSweepReq_eyeSweepTestResults_bits[5]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_6  (vif.rxEyeSweepReq_eyeSweepTestResults_bits[6]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_7  (vif.rxEyeSweepReq_eyeSweepTestResults_bits[7]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_8  (vif.rxEyeSweepReq_eyeSweepTestResults_bits[8]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_9  (vif.rxEyeSweepReq_eyeSweepTestResults_bits[9]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_10 (vif.rxEyeSweepReq_eyeSweepTestResults_bits[10]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_11 (vif.rxEyeSweepReq_eyeSweepTestResults_bits[11]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_12 (vif.rxEyeSweepReq_eyeSweepTestResults_bits[12]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_13 (vif.rxEyeSweepReq_eyeSweepTestResults_bits[13]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_14 (vif.rxEyeSweepReq_eyeSweepTestResults_bits[14]),
    .io_rxEyeSweepReqIntfIo_eyeSweepTestResults_bits_15 (vif.rxEyeSweepReq_eyeSweepTestResults_bits[15]),
    .io_rxEyeSweepReqIntfIo_start                        (vif.rxEyeSweepReq_start),
    .io_rxEyeSweepReqIntfIo_linkTrainingParameters_clockPhase    (vif.rxEyeSweepReq_clockPhase),
    .io_rxEyeSweepReqIntfIo_linkTrainingParameters_dataPattern   (vif.rxEyeSweepReq_dataPattern),
    .io_rxEyeSweepReqIntfIo_linkTrainingParameters_validPattern  (vif.rxEyeSweepReq_validPattern),
    .io_rxEyeSweepReqIntfIo_linkTrainingParameters_patternMode   (vif.rxEyeSweepReq_patternMode),
    .io_rxEyeSweepReqIntfIo_linkTrainingParameters_iterationCount(vif.rxEyeSweepReq_iterationCount),
    .io_rxEyeSweepReqIntfIo_linkTrainingParameters_idleCount     (vif.rxEyeSweepReq_idleCount),
    .io_rxEyeSweepReqIntfIo_linkTrainingParameters_burstCount    (vif.rxEyeSweepReq_burstCount),
    .io_rxEyeSweepReqIntfIo_linkTrainingParameters_maxErrorThreshold(vif.rxEyeSweepReq_maxErrorThreshold),
    .io_rxEyeSweepReqIntfIo_linkTrainingParameters_comparisonMode(vif.rxEyeSweepReq_comparisonMode),
    .io_rxEyeSweepReqIntfIo_patternType                          (vif.rxEyeSweepReq_patternType),

    .io_txPtTestRespIntfIo_done      (vif.txPtTestResp_done),
    .io_txPtTestRespIntfIo_start     (vif.txPtTestResp_start),
    .io_txPtTestRespIntfIo_patternType(vif.txPtTestResp_patternType),
    .io_txEyeSweepRespIntfIo_done    (vif.txEyeSweepResp_done),
    .io_txEyeSweepRespIntfIo_start   (vif.txEyeSweepResp_start),
    .io_txEyeSweepRespIntfIo_patternType(vif.txEyeSweepResp_patternType),
    .io_rxPtTestRespIntfIo_done      (vif.rxPtTestResp_done),
    .io_rxPtTestRespIntfIo_start     (vif.rxPtTestResp_start),
    .io_rxPtTestRespIntfIo_patternType(vif.rxPtTestResp_patternType),
    .io_rxEyeSweepRespIntfIo_done    (vif.rxEyeSweepResp_done),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_valid(vif.rxEyeSweepResp_remoteEyeSweepTestResults_valid),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_0(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[0]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_1(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[1]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_2(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[2]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_3(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[3]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_4(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[4]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_5(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[5]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_6(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[6]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_7(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[7]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_8(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[8]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_9(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[9]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_10(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[10]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_11(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[11]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_12(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[12]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_13(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[13]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_14(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[14]),
    .io_rxEyeSweepRespIntfIo_remoteEyeSweepTestResults_bits_15(vif.rxEyeSweepResp_remoteEyeSweepTestResults_bits[15]),
    .io_rxEyeSweepRespIntfIo_start   (vif.rxEyeSweepResp_start),
    .io_rxEyeSweepRespIntfIo_patternType(vif.rxEyeSweepResp_patternType),

    .io_trainingCtrl_txSelfCalStart  (vif.trainingCtrl_txSelfCalStart),
    .io_trainingCtrl_rxClkCalStart   (vif.trainingCtrl_rxClkCalStart),
    .io_trainingCtrl_txSelfCalDone   (vif.trainingCtrl_txSelfCalDone),
    .io_trainingCtrl_rxClkCalDone    (vif.trainingCtrl_rxClkCalDone),
    .io_trainingCtrl_capableTest_isTxType(vif.trainingCtrl_capableTest_isTxType),
    .io_trainingCtrl_capableTest_isRxType(vif.trainingCtrl_capableTest_isRxType),
    .io_trainingCtrl_capableTest_testKind(vif.trainingCtrl_capableTest_testKind),
    .io_trainingCtrl_req_readyForReq (vif.trainingCtrl_req_readyForReq),
    .io_trainingCtrl_req_start       (vif.trainingCtrl_req_start),
    .io_trainingCtrl_req_testKind    (vif.trainingCtrl_req_testKind),
    .io_trainingCtrl_req_complete    (vif.trainingCtrl_req_complete),
    .io_trainingCtrl_resp_inProgress (vif.trainingCtrl_resp_inProgress),
    .io_trainingCtrl_resp_done       (vif.trainingCtrl_resp_done),
    .io_trainingCtrl_resp_results_valid(vif.trainingCtrl_resp_results_valid),
    .io_trainingCtrl_resp_results_bits_0(vif.trainingCtrl_resp_results_bits[0]),
    .io_trainingCtrl_resp_results_bits_1(vif.trainingCtrl_resp_results_bits[1]),
    .io_trainingCtrl_resp_results_bits_2(vif.trainingCtrl_resp_results_bits[2]),
    .io_trainingCtrl_resp_results_bits_3(vif.trainingCtrl_resp_results_bits[3]),
    .io_trainingCtrl_resp_results_bits_4(vif.trainingCtrl_resp_results_bits[4]),
    .io_trainingCtrl_resp_results_bits_5(vif.trainingCtrl_resp_results_bits[5]),
    .io_trainingCtrl_resp_results_bits_6(vif.trainingCtrl_resp_results_bits[6]),
    .io_trainingCtrl_resp_results_bits_7(vif.trainingCtrl_resp_results_bits[7]),
    .io_trainingCtrl_resp_results_bits_8(vif.trainingCtrl_resp_results_bits[8]),
    .io_trainingCtrl_resp_results_bits_9(vif.trainingCtrl_resp_results_bits[9]),
    .io_trainingCtrl_resp_results_bits_10(vif.trainingCtrl_resp_results_bits[10]),
    .io_trainingCtrl_resp_results_bits_11(vif.trainingCtrl_resp_results_bits[11]),
    .io_trainingCtrl_resp_results_bits_12(vif.trainingCtrl_resp_results_bits[12]),
    .io_trainingCtrl_resp_results_bits_13(vif.trainingCtrl_resp_results_bits[13]),
    .io_trainingCtrl_resp_results_bits_14(vif.trainingCtrl_resp_results_bits[14]),
    .io_trainingCtrl_resp_results_bits_15(vif.trainingCtrl_resp_results_bits[15]),
    .io_trainingCtrl_remoteRxSweepResults_valid(vif.trainingCtrl_remoteRxSweepResults_valid),
    .io_trainingCtrl_remoteRxSweepResults_bits_0(vif.trainingCtrl_remoteRxSweepResults_bits[0]),
    .io_trainingCtrl_remoteRxSweepResults_bits_1(vif.trainingCtrl_remoteRxSweepResults_bits[1]),
    .io_trainingCtrl_remoteRxSweepResults_bits_2(vif.trainingCtrl_remoteRxSweepResults_bits[2]),
    .io_trainingCtrl_remoteRxSweepResults_bits_3(vif.trainingCtrl_remoteRxSweepResults_bits[3]),
    .io_trainingCtrl_remoteRxSweepResults_bits_4(vif.trainingCtrl_remoteRxSweepResults_bits[4]),
    .io_trainingCtrl_remoteRxSweepResults_bits_5(vif.trainingCtrl_remoteRxSweepResults_bits[5]),
    .io_trainingCtrl_remoteRxSweepResults_bits_6(vif.trainingCtrl_remoteRxSweepResults_bits[6]),
    .io_trainingCtrl_remoteRxSweepResults_bits_7(vif.trainingCtrl_remoteRxSweepResults_bits[7]),
    .io_trainingCtrl_remoteRxSweepResults_bits_8(vif.trainingCtrl_remoteRxSweepResults_bits[8]),
    .io_trainingCtrl_remoteRxSweepResults_bits_9(vif.trainingCtrl_remoteRxSweepResults_bits[9]),
    .io_trainingCtrl_remoteRxSweepResults_bits_10(vif.trainingCtrl_remoteRxSweepResults_bits[10]),
    .io_trainingCtrl_remoteRxSweepResults_bits_11(vif.trainingCtrl_remoteRxSweepResults_bits[11]),
    .io_trainingCtrl_remoteRxSweepResults_bits_12(vif.trainingCtrl_remoteRxSweepResults_bits[12]),
    .io_trainingCtrl_remoteRxSweepResults_bits_13(vif.trainingCtrl_remoteRxSweepResults_bits[13]),
    .io_trainingCtrl_remoteRxSweepResults_bits_14(vif.trainingCtrl_remoteRxSweepResults_bits[14]),
    .io_trainingCtrl_remoteRxSweepResults_bits_15(vif.trainingCtrl_remoteRxSweepResults_bits[15])
  );

  initial begin
    uvm_config_db#(virtual mbtrain_if)::set(null, "*", "mbtrain_vif", vif);
    run_test();
  end

endmodule
