// AUTO LinkTrainingSM ports
  logic  clock;
  logic  reset;
  logic  io_pwrGood;
  logic [9:0] io_retryTrainingAmt;
  logic  io_localPhyParamSettings_valid;
  logic [4:0] io_localPhyParamSettings_bits_voltageSwing;
  logic [3:0] io_localPhyParamSettings_bits_maxDataRate;
  logic  io_localPhyParamSettings_bits_clockMode;
  logic  io_localPhyParamSettings_bits_clockPhase;
  logic  io_localPhyParamSettings_bits_ucieSx8;
  logic  io_localPhyParamSettings_bits_sbFeatExt;
  logic  io_localPhyParamSettings_bits_txAdjRuntime;
  logic [1:0] io_localPhyParamSettings_bits_moduleId;
  logic [3:0] io_linkTrainingParameters_clockPhase;
  logic [2:0] io_linkTrainingParameters_dataPattern;
  logic [2:0]  io_linkTrainingParameters_validPattern;
  logic  io_linkTrainingParameters_patternMode;
  logic [15:0] io_linkTrainingParameters_iterationCount;
  logic [15:0] io_linkTrainingParameters_idleCount;
  logic [15:0] io_linkTrainingParameters_burstCount;
  logic [15:0] io_linkTrainingParameters_maxErrorThreshold;
  logic  io_linkTrainingParameters_comparisonMode;
  wire  io_swStartLinkTraining;
  logic [15:0] io_maxErrorThresholdPerLane;
  logic  io_changeInRuntimeLinkCtrlRegsDetected;
  logic  io_runtimeLinkCtrlBusyBit;
  logic  io_runtimeRequestForRepair;
  wire [3:0] io_ltState;
  wire [4:0] io_currentState;
  wire  io_trainingTimedout;
  wire  io_fatalTrainingError;
  wire  io_forceRdiLinkError;
  wire  io_doLaneReversal;
  wire [2:0] io_localTxFunctionalLanes;
  wire [2:0]  io_remoteTxFunctionalLanes;
  wire  io_negotiatedPhyParamSettings_valid;
  wire [4:0] io_negotiatedPhyParamSettings_bits_voltageSwing;
  wire [3:0] io_negotiatedPhyParamSettings_bits_maxDataRate;
  wire  io_negotiatedPhyParamSettings_bits_clockMode;
  wire  io_negotiatedPhyParamSettings_bits_clockPhase;
  wire  io_negotiatedPhyParamSettings_bits_ucieSx8;
  wire  io_negotiatedPhyParamSettings_bits_sbFeatExt;
  wire  io_negotiatedPhyParamSettings_bits_txAdjRuntime;
  wire [1:0] io_negotiatedPhyParamSettings_bits_moduleId;
  wire  io_rxClkCalSendFwClkPattern;
  wire  io_rxClkCalSendTrkPattern;
  wire  io_scramblerReset;
  logic [3:0] io_rdi_plStateSts;
  logic [3:0]  io_rdi_lpStateReq;
  wire  io_rdi_doRdiBringup;
  logic  io_rdi_doingRdiBringUp;
  wire  io_sbCtrlIo_txEn;
  wire  io_sbCtrlIo_rxEn;
  wire  io_sbCtrlIo_rxTxMode;
  wire  io_sbCtrlIo_sbReset;
  wire  io_sbCtrlIo_freezeAcceptingPackets;
  logic  io_sbCtrlIo_allPacketsSent;
  wire  io_mbCtrlIo_txDataEn_0;
  wire  io_mbCtrlIo_txDataEn_1;
  wire  io_mbCtrlIo_txDataEn_2;
  wire  io_mbCtrlIo_txDataEn_3;
  wire  io_mbCtrlIo_txDataEn_4;
  wire  io_mbCtrlIo_txDataEn_5;
  wire  io_mbCtrlIo_txDataEn_6;
  wire  io_mbCtrlIo_txDataEn_7;
  wire  io_mbCtrlIo_txDataEn_8;
  wire  io_mbCtrlIo_txDataEn_9;
  wire  io_mbCtrlIo_txDataEn_10;
  wire  io_mbCtrlIo_txDataEn_11;
  wire  io_mbCtrlIo_txDataEn_12;
  wire  io_mbCtrlIo_txDataEn_13;
  wire  io_mbCtrlIo_txDataEn_14;
  wire  io_mbCtrlIo_txDataEn_15;
  wire  io_mbCtrlIo_txClkEn;
  wire  io_mbCtrlIo_txValidEn;
  wire  io_mbCtrlIo_txTrackEn;
  wire  io_mbCtrlIo_rxDataEn_0;
  wire  io_mbCtrlIo_rxDataEn_1;
  wire  io_mbCtrlIo_rxDataEn_2;
  wire  io_mbCtrlIo_rxDataEn_3;
  wire  io_mbCtrlIo_rxDataEn_4;
  wire  io_mbCtrlIo_rxDataEn_5;
  wire  io_mbCtrlIo_rxDataEn_6;
  wire  io_mbCtrlIo_rxDataEn_7;
  wire  io_mbCtrlIo_rxDataEn_8;
  wire  io_mbCtrlIo_rxDataEn_9;
  wire  io_mbCtrlIo_rxDataEn_10;
  wire  io_mbCtrlIo_rxDataEn_11;
  wire  io_mbCtrlIo_rxDataEn_12;
  wire  io_mbCtrlIo_rxDataEn_13;
  wire  io_mbCtrlIo_rxDataEn_14;
  wire  io_mbCtrlIo_rxDataEn_15;
  wire  io_mbCtrlIo_rxClkEn;
  wire  io_mbCtrlIo_rxValidEn;
  wire  io_mbCtrlIo_rxTrackEn;
  logic  io_phyCtrlIo_pllLock;
  wire [3:0] io_phyCtrlIo_freqSel;
  wire  io_phyCtrlIo_doElectricalIdleRx;
  wire  io_phyCtrlIo_doElectricalIdleTx;
  wire [4:0] io_phyTrainIo_ltsmState;
  wire  io_phyTrainIo_mbTrain_txSelfCalStart;
  wire  io_phyTrainIo_mbTrain_rxClkCalStart;
  logic  io_phyTrainIo_mbTrain_txSelfCalDone;
  logic  io_phyTrainIo_mbTrain_rxClkCalDone;
  wire  io_phyTrainIo_mbTrain_capableTest_isTxType;
  wire  io_phyTrainIo_mbTrain_capableTest_isRxType;
  wire [1:0] io_phyTrainIo_mbTrain_capableTest_testKind;
  wire  io_phyTrainIo_mbTrain_req_readyForReq;
  logic  io_phyTrainIo_mbTrain_req_start;
  logic [1:0] io_phyTrainIo_mbTrain_req_testKind;
  logic  io_phyTrainIo_mbTrain_req_complete;
  wire  io_phyTrainIo_mbTrain_resp_inProgress;
  wire  io_phyTrainIo_mbTrain_resp_done;
  wire  io_phyTrainIo_mbTrain_resp_results_valid;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_0;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_1;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_2;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_3;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_4;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_5;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_6;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_7;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_8;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_9;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_10;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_11;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_12;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_13;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_14;
  wire  io_phyTrainIo_mbTrain_resp_results_bits_15;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_valid;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_0;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_1;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_2;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_3;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_4;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_5;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_6;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_7;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_8;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_9;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_10;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_11;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_12;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_13;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_14;
  wire  io_phyTrainIo_mbTrain_remoteRxSweepResults_bits_15;
  wire  io_phyTrainIo_mbInit_selfCalStart;
  logic  io_phyTrainIo_mbInit_selfCalDone;
  wire  io_phyTrainIo_localStatus_doingTxEyeWidthSweep;
  wire  io_phyTrainIo_localStatus_doingTxPointTest;
  wire  io_phyTrainIo_localStatus_doingRxEyeWidthSweep;
  wire  io_phyTrainIo_localStatus_doingRxPointTest;
  wire  io_phyTrainIo_remoteStatus_doingTxEyeWidthSweep;
  wire  io_phyTrainIo_remoteStatus_doingTxPointTest;
  wire  io_phyTrainIo_remoteStatus_doingRxEyeWidthSweep;
  wire  io_phyTrainIo_remoteStatus_doingRxPointTest;
  wire  io_phyTrainIo_eyeSweepCtrl_waitingForCommand;
  logic  io_phyTrainIo_eyeSweepCtrl_step;
  logic  io_phyTrainIo_eyeSweepCtrl_doneStepping;
  logic  io_sbLaneIo_tx_ready;
  wire  io_sbLaneIo_tx_valid;
  wire [127:0] io_sbLaneIo_tx_bits_data;
  wire  io_sbLaneIo_rx_ready;
  logic  io_sbLaneIo_rx_valid;
  logic [127:0] io_sbLaneIo_rx_bits_data;
  logic  io_patternWriterIo_req_ready;
  wire  io_patternWriterIo_req_valid;
  wire [1:0] io_patternWriterIo_req_bits_patternType;
  wire [2:0] io_patternWriterIo_functionalLanes;
  logic  io_patternWriterIo_resp_complete;
  logic  io_patternReaderIo_req_ready;
  wire  io_patternReaderIo_req_valid;
  wire [1:0] io_patternReaderIo_req_bits_patternType;
  wire  io_patternReaderIo_req_bits_comparisonMode;
  wire [15:0] io_patternReaderIo_req_bits_errorThreshold;
  wire  io_patternReaderIo_req_bits_doConsecutiveCount;
  wire  io_patternReaderIo_req_bits_done;
  wire  io_patternReaderIo_req_bits_clear;
  wire [2:0] io_patternReaderIo_functionalLanes;
  logic  io_patternReaderIo_resp_valid;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_0;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_1;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_2;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_3;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_4;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_5;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_6;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_7;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_8;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_9;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_10;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_11;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_12;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_13;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_14;
  logic  io_patternReaderIo_resp_bits_perLaneStatusBits_15;
  logic  io_patternReaderIo_resp_bits_aggregateStatus;
